### ISSUE TITLE
Add ability to configure annotation via config file

### ISSUE THREAD

**Issue by DavyJ0nes** [DavyJ0nes/grafana-notifier#1]
Thinking this would be another mode of use that would take in a yaml(?) config file with structure like:

```yaml
---
tags:
  - env:production
  - api-server
  - version:1.1.0

text: <-
  Deployed Service: api-server
  Version: 1.1.0
```
